# apiVersion: salaboy.com/v1alpha1
# kind: RedisDB
# metadata:
#   labels:
#    crossplane.io/claim-name: redis
#   name: redis
#   namespace: myapps
# spec:
#   compositionSelector:
#     matchLabels:
#       provider: local
#       type: dev
#   parameters:
#     mockData: true
#     size: small
#   writeConnectionSecretToRef:
#     name: redis-secret
