apiVersion: salaboy.com/v1alpha1
kind: Redis
metadata:
  name: myredis
  namespace: appworkloads
spec:
  writeConnectionSecretToRef:
    name: redis-conn
  compositionSelector:
    matchLabels:
      provider: local
      type: dev
  parameters:
    mockData: true
    size: small