apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hellocartoapp-ingress
  namespace: appworkloads
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  ingressClassName: nginx-internal
  rules:
  - host: simplepy.apps.aznpiplatops.az.ga.afginc.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hellocartoapp
            port:
              number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellocartoapp
  namespace: appworkloads
  labels:
    carto.run/workload-name: hellocartoapp
    run: hellocartoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hellocartoapp
  template:
    metadata:
      labels:
        run: hellocartoapp
    spec:
      containers:
      - name: appworkloads
        image: ghcr.io/ssanden-gaig/example-basic-sc-hellocartoapp@sha256:9eb238cb72e1e6f8e29d68ff8c829cb61f96c5c3ddf05f33eeb038c9a61fab12
        securityContext:
          runAsUser: 1000
      imagePullSecrets:
      - name: image-pull-sa
---
apiVersion: v1
kind: Service
metadata:
  name: hellocartoapp
  namespace: appworkloads
  labels:
    service: hellocartoapp
    app: hellocartoapp
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8080
  selector:
    run: hellocartoapp

