apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simplepy
  namespace: myapps
spec:
  ingressClassName: cilium
  rules:
  - host: *.apps.az.ga.afginc.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simplepy
            port:
              name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplepy
  namespace: myapps
  labels:
    run: simplepy
spec:
  replicas: 1
  selector:
    matchLabels:
      run: simplepy
  template:
    metadata:
      labels:
        run: simplepy
    spec:
      containers:
      - name: simplepy
        image: ghcr.io/ssanden-gaig/simplepy@sha256:5455eb0b6e0cbc0b1b154b7d33d87b8ff787c10382a78bab4910bfde80a7bd9f
        securityContext:
          runAsUser: 1000
      imagePullSecrets:
      - name: image-pull-sa
---
apiVersion: v1
kind: Service
metadata:
  name: simplepy
  namespace: myapps
  labels:
    service: simplepy
    app: simplepy
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 8080
  selector:
    run: simplepy

