apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simplepy
  namespace: myapps
spec:
  ingressClassName: cilium
  rules:
  - host: "*.apps.az.ga.afginc.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simplepy
            port:
              name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplepy
  namespace: myapps
  labels:
    run: simplepy
spec:
  replicas: 1
  selector:
    matchLabels:
      run: simplepy
  template:
    metadata:
      labels:
        run: simplepy
    spec:
      containers:
      - name: simplepy
        image: ghcr.io/ssanden-gaig/pysimple:v1.2
        securityContext:
          runAsUser: 1000
        resources:
          limits:
            cpu: "100m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name                
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName    
      imagePullSecrets:
      - name: image-pull-sa
---
apiVersion: v1
kind: Service
metadata:
  name: simplepy
  namespace: myapps
  labels:
    service: simplepy
    app: simplepy
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 8080
  selector:
    run: simplepy

