apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hellocartoapp-ingress
  namespace: workloads
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  ingressClassName: nginx-internal
  rules:
  - host: simplepy.az.ga.afginc.com
    http:
      paths:
      - path: /hello
        pathType: Prefix
        backend:
          service:
            name: hellocartoapp
            port:
              number: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellocartoapp
  namespace: workloads
  labels:
    carto.run/workload-name: hellocartoapp
    run: hellocartoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hellocartoapp
  template:
    metadata:
      labels:
        run: hellocartoapp
    spec:
      containers:
      - name: workload
        image: ghcr.io/ssanden-gaig/example-basic-sc-hellocartoapp@sha256:684dc1585e9c1de638245417cddc33fd031d7d60bd0f986f1b2bd64f51b8e25a
        securityContext:
          runAsUser: 1000
      imagePullSecrets:
      - name: image-pull-sa
---
apiVersion: v1
kind: Service
metadata:
  name: hellocartoapp
  namespace: workloads
  labels:
    service: hellocartoapp
    app: hellocartoapp
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  selector:
    run: hellocartoapp

