apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simplepy-ingress
  namespace: myapps
spec:
  ingressClassName: nginx-internal
  rules:
  - host: simplepy.apps.aznpiplatops.az.ga.afginc.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simplepy
            port:
              name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplepy
  namespace: myapps
  labels:
    carto.run/workload-name: simplepy
    run: simplepy
spec:
  replicas: 1
  selector:
    matchLabels:
      run: simplepy
  template:
    metadata:
      labels:
        run: simplepy
    spec:
      containers:
      - name: simplepy
        image: ghcr.io/ssanden-gaig/simplepy@sha256:b342bd385031c0358415482a224114a4e2b3711b174cce3f1ae9b641286b35e7
        securityContext:
          runAsUser: 1000
      imagePullSecrets:
      - name: image-pull-sa
---
apiVersion: v1
kind: Service
metadata:
  name: simplepy
  namespace: myapps
  labels:
    service: simplepy
    app: simplepy
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 8080
  selector:
    run: simplepy

