apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hellocartoapp-ingress
  namespace: appworkloads
spec:
  ingressClassName: nginx-internal
  rules:
  - host: simplepy.apps.aznpiplatops.az.ga.afginc.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hellocartoapp
            port:
              name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellocartoapp
  namespace: appworkloads
  labels:
    carto.run/workload-name: hellocartoapp
    run: hellocartoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hellocartoapp
  template:
    metadata:
      labels:
        run: hellocartoapp
    spec:
      containers:
      - name: appworkloads
        image: ghcr.io/ssanden-gaig/example-basic-sc-hellocartoapp@sha256:97e0ec1011f11cc599d9ddcfa5a702824bae98058ac85ad2e6b528e1b6ef09f0
        securityContext:
          runAsUser: 1000
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mydb-redis
              key: redis-password
      imagePullSecrets:
      - name: image-pull-sa
---
apiVersion: v1
kind: Service
metadata:
  name: hellocartoapp
  namespace: appworkloads
  labels:
    service: hellocartoapp
    app: hellocartoapp
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 8080
  selector:
    run: hellocartoapp

