name: Build and Push to Azure ACR

on:
    push:
        branches:
            - main
jobs:
  build-and-push:
    env:
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_REGISTRY:  ${{ vars.ACR_REGISTRY }}
      IMG_NAME: "python-sample-app"
    runs-on: arc-runners
    environment: NP
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # - name: SetAppName
    #   run: 'echo "IMG_NAME=$(echo ${env.ACR_REGISTRY})/$(echo ${env.IMG_NAME})" >> $GITHUB_ENV'
    - id: login
      uses: docker/login-action@v1 
      with:
       username: ${{env.ACR_USERNAME}}
       password: ${{env.ACR_PASSWORD}}
       registry: ${{ vars.ACR_REGISTRY }} 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: build and push
      uses: docker/build-push-action@v5
      with:
         platforms: linux/amd64
         push: true
         tags: ${{ vars.ACR_REGISTRY }}/myapp:v1